#!/usr/bin/env python3

import os
import openai
from spinner import Spinner

spinner = Spinner()

openai.api_key = os.getenv("OPENAI_API_KEY")

def main():
    word = input("> ")

    spinner.start()
    response = openai.Completion.create(
      model="text-curie-001",
      prompt="Translate the following to spanish: " + word,
      max_tokens=1000,
      temperature=0,
    )
    spinner.stop()

    text = response["choices"][0]["text"]
    text = text.strip()


    print("\033[96m" + "> " + text + "\033[00m")


if __name__ == "__main__":
    main()
